export const colors = {
  primary: '#785900',
  onPrimary: '#ffffff',
  primaryContainer: '#ffc107',
  onPrimaryContainer: '#6d5100',
  primaryFixed: '#ffdf9e',
  primaryFixedDim: '#fabd00',
  onPrimaryFixed: '#261a00',
  onPrimaryFixedVariant: '#5b4300',
  inversePrimary: '#fabd00',
  secondary: '#625f4d',
  onSecondary: '#ffffff',
  secondaryContainer: '#e6e0c9',
  onSecondaryContainer: '#676351',
  secondaryFixed: '#e9e2cc',
  secondaryFixedDim: '#ccc6b1',
  onSecondaryFixed: '#1e1c0e',
  onSecondaryFixedVariant: '#4a4737',
  tertiary: '#006e1c',
  onTertiary: '#ffffff',
  tertiaryContainer: '#7ce17b',
  onTertiaryContainer: '#006419',
  tertiaryFixed: '#94f990',
  tertiaryFixedDim: '#78dc77',
  onTertiaryFixed: '#002204',
  onTertiaryFixedVariant: '#005313',
  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
  surface: '#fcf9f8',
  surfaceDim: '#dcd9d9',
  surfaceBright: '#fcf9f8',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f6f3f2',
  surfaceContainer: '#f0eded',
  surfaceContainerHigh: '#eae7e7',
  surfaceContainerHighest: '#e5e2e1',
  onSurface: '#1b1c1c',
  onSurfaceVariant: '#4f4632',
  inverseSurface: '#303030',
  inverseOnSurface: '#f3f0ef',
  outline: '#827660',
  outlineVariant: '#d4c5ab',
  background: '#fcf9f8',
  onBackground: '#1b1c1c',
  surfaceVariant: '#e5e2e1',
  surfaceTint: '#785900',
  white: '#ffffff',
  black: '#000000',
  // Semantic tokens from prototypes
  metricBg1: '#FFF8E1',
  metricBorder1: '#FFF1C1',
  metricText1: '#785900',
  metricBg2: '#FFEBEE',
  metricBorder2: '#FFCDD2',
  metricText2: '#C62828',
  metricBg3: '#E3F2FD',
  metricBorder3: '#BBDEFB',
  metricText3: '#1565C0',
  metricBg4: '#E8F5E9',
  metricBorder4: '#C8E6C9',
  metricText4: '#2E7D32',
  filterActive: '#ffc107',
  filterInactive: '#e5e2e1',
  pillBg: '#FFF8E1',
  pillText: '#785900',
  // Status colors from orders
  pendiente: '#FF9800',
  pendienteBg: '#FFF8E1',
  enCocina: '#2196F3',
  enCocinaBg: '#E3F2FD',
  listo: '#4CAF50',
  listoBg: '#E8F5E9',
  entregado: '#9E9E9E',
  entregadoBg: '#F5F5F5',
};

export const typography = {
  displayLg: {
    fontFamily: 'Poppins',
    fontSize: 32,
    fontWeight: '700',
    lineHeight: 40,
    letterSpacing: -0.64,
  },
  displayLgMobile: {
    fontFamily: 'Poppins',
    fontSize: 28,
    fontWeight: '700',
    lineHeight: 36,
    letterSpacing: -0.56,
  },
  headlineMd: {
    fontFamily: 'Poppins',
    fontSize: 24,
    fontWeight: '600',
    lineHeight: 32,
  },
  titleSm: {
    fontFamily: 'Poppins',
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 24,
  },
  bodyMd: {
    fontFamily: 'Inter',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 24,
  },
  bodySm: {
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 20,
  },
  labelBold: {
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
  },
  buttonText: {
    fontFamily: 'Inter',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 16,
    letterSpacing: 0.16,
  },
  valueDisplay: {
    fontFamily: 'Be Vietnam Pro',
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 24,
  },
  productTitle: {
    fontFamily: 'Be Vietnam Pro',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 24,
  },
  labelCaption: {
    fontFamily: 'Inter',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 16,
    letterSpacing: 0.24,
  },
  metadata: {
    fontFamily: 'Inter',
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 16,
  },
};

export const spacing = {
  xs: 4,
  base: 8,
  sm: 12,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
  containerMax: 440,
  gutter: 16,
};

export const borderRadius = {
  sm: 4,
  md: 8,
  lg: 12,
  xl: 16,
  full: 9999,
};

export const shadows = {
  sm: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  md: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  lg: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 8,
  },
};
